import type { DepartmentKey } from '@vigoros/contracts'

/** Every position in the company. Phase 1 positions have full role definitions in ./roles. */
export interface Position {
  key: string
  title: string
  department: DepartmentKey
  scope: 'studio' | 'character'
  phase: 1 | 2 | 3 | 4 | 5
}

export const POSITIONS: readonly Position[] = [
  {
    key: 'studio-director',
    title: 'Studio Director',
    department: 'executive',
    scope: 'studio',
    phase: 1,
  },
  {
    key: 'head-of-strategy',
    title: 'Head of Strategy',
    department: 'executive',
    scope: 'studio',
    phase: 4,
  },
  {
    key: 'operations-manager',
    title: 'Operations Manager',
    department: 'executive',
    scope: 'studio',
    phase: 4,
  },
  { key: 'showrunner', title: 'Showrunner', department: 'creative', scope: 'character', phase: 4 },
  {
    key: 'comedy-writer-a',
    title: 'Comedy Writer A',
    department: 'creative',
    scope: 'character',
    phase: 1,
  },
  {
    key: 'comedy-writer-b',
    title: 'Comedy Writer B',
    department: 'creative',
    scope: 'character',
    phase: 1,
  },
  {
    key: 'trend-researcher',
    title: 'Trend Researcher',
    department: 'creative',
    scope: 'character',
    phase: 1,
  },
  {
    key: 'script-editor',
    title: 'Script Editor',
    department: 'creative',
    scope: 'character',
    phase: 5,
  },
  {
    key: 'creative-reviewer',
    title: 'Creative Reviewer',
    department: 'creative',
    scope: 'character',
    phase: 1,
  },
  {
    key: 'character-development',
    title: 'Character Development',
    department: 'creative',
    scope: 'studio',
    phase: 5,
  },
  {
    key: 'production-manager',
    title: 'Production Manager',
    department: 'production',
    scope: 'character',
    phase: 1,
  },
  {
    key: 'storyboard-artist',
    title: 'Storyboard Artist',
    department: 'production',
    scope: 'character',
    phase: 5,
  },
  {
    key: 'prompt-engineer',
    title: 'Prompt Engineer',
    department: 'production',
    scope: 'character',
    phase: 2,
  },
  {
    key: 'animation-coordinator',
    title: 'Animation Coordinator',
    department: 'production',
    scope: 'character',
    phase: 3,
  },
  {
    key: 'continuity-supervisor',
    title: 'Continuity Supervisor',
    department: 'production',
    scope: 'character',
    phase: 2,
  },
  {
    key: 'video-editor',
    title: 'Video Editor',
    department: 'production',
    scope: 'character',
    phase: 3,
  },
  {
    key: 'voice-supervisor',
    title: 'Voice Supervisor',
    department: 'production',
    scope: 'character',
    phase: 3,
  },
  {
    key: 'social-strategist',
    title: 'Social Strategist',
    department: 'growth',
    scope: 'character',
    phase: 5,
  },
  { key: 'trend-analyst', title: 'Trend Analyst', department: 'growth', scope: 'studio', phase: 5 },
  {
    key: 'publishing-manager',
    title: 'Publishing Manager',
    department: 'growth',
    scope: 'character',
    phase: 3,
  },
  {
    key: 'community-analyst',
    title: 'Community Analyst',
    department: 'growth',
    scope: 'character',
    phase: 5,
  },
  {
    key: 'growth-experimentation',
    title: 'Growth Experimentation',
    department: 'growth',
    scope: 'character',
    phase: 5,
  },
  {
    key: 'audience-research',
    title: 'Audience Research',
    department: 'growth',
    scope: 'character',
    phase: 5,
  },
  {
    key: 'performance-analyst',
    title: 'Performance Analyst',
    department: 'growth',
    scope: 'character',
    phase: 1,
  },
  {
    key: 'commercial-strategist',
    title: 'Commercial Strategist',
    department: 'commercial',
    scope: 'studio',
    phase: 5,
  },
  {
    key: 'partnerships-researcher',
    title: 'Partnerships Researcher',
    department: 'commercial',
    scope: 'studio',
    phase: 5,
  },
  {
    key: 'merchandising-strategist',
    title: 'Merchandising Strategist',
    department: 'commercial',
    scope: 'character',
    phase: 5,
  },
  {
    key: 'financial-analyst',
    title: 'Financial Analyst',
    department: 'commercial',
    scope: 'studio',
    phase: 5,
  },
  {
    key: 'agent-operations',
    title: 'Agent Operations',
    department: 'operations',
    scope: 'studio',
    phase: 4,
  },
  {
    key: 'workflow-reliability',
    title: 'Workflow Reliability',
    department: 'operations',
    scope: 'studio',
    phase: 4,
  },
  {
    key: 'platform-compliance',
    title: 'Platform Compliance',
    department: 'operations',
    scope: 'studio',
    phase: 4,
  },
  {
    key: 'quality-assurance',
    title: 'Quality Assurance',
    department: 'operations',
    scope: 'studio',
    phase: 4,
  },
]
