export {
  buildMerkleTree,
  bytesToHex,
  hashPair,
  hexToBytes,
  inclusionProof,
  isHexDigest,
  sha256Bytes,
  verifyInclusion,
  type InclusionProof,
  type MerkleTree,
  type ProofStep,
} from './merkle'
export {
  DEFAULT_CALENDARS,
  OtsClient,
  OtsError,
  getUpgrade,
  parseAttestations,
  stampDigest,
  type Attestation,
  type BitcoinAttestation,
  type OtsAttempt,
  type OtsClientOptions,
  type OtsErrorCode,
  type OtsProof,
  type PendingAttestation,
  type UnknownAttestation,
} from './opentimestamps'
export { sealDay, type SealedDay } from './seal'
